In [ ]:
!python -m spacy download en_core_web_md

In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pipeline_functions import encode_stockcode

In [2]:
df = pd.read_excel('online_retail_II.xlsx')
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

## NLP Describiton Performance

### Delete NaN

In [10]:
df2 = df[~df['Description'].isna()]
df2

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [15]:
df3 = df2.groupby(['StockCode','Description'],as_index=False).count()
df3

,StockCode,Description,Invoice,Quantity,InvoiceDate,Price,Customer ID,Country
0,10002,INFLATABLE POLITICAL GLOBE,327,327,327,327,275,327
1,10080,GROOVY CACTUS INFLATABLE,6,6,6,6,6,6
2,10109,BENDY COLOUR PENCILS,1,1,1,1,1,1
3,10120,DOGGY RUBBER,48,48,48,48,37,48
4,10120,Zebra invcing error,1,1,1,1,0,1
...,...,...,...,...,...,...,...,...
5065,gift_0001_40,Dotcomgiftshop Gift Voucher Â£40.00,2,2,2,2,0,2
5066,gift_0001_50,Dotcomgiftshop Gift Voucher Â£50.00,2,2,2,2,0,2
5067,gift_0001_70,Dotcomgiftshop Gift Voucher Â£70.00,1,1,1,1,0,1
5068,gift_0001_80,Dotcomgiftshop Gift Voucher Â£80.00,2,2,2,2,0,2
5069,m,Manual,4,4,4,4,0,4

In [16]:
import pandas as pd
import nltk
#import IProgress
import ipywidgets
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from tqdm.notebook import tqdm
tqdm.pandas()

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Define the preprocessing function
def preprocess_text(text):
    # Tokenize the text
    tokens = word_tokenize(str(text).lower())
    # Remove stop words
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    # Lemmatize the words
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    # Join the tokens back into a string
    #preprocessed_text = ' '.join(tokens)
    return tokens

# Apply the preprocessing function to the 'Description' column
df3['Preprocessed Description'] = df3['Description'].progress_apply(preprocess_text)

df3

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\wkosi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\wkosi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\wkosi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

  0%|          | 0/5070 [00:00<?, ?it/s]

,StockCode,Description,Invoice,Quantity,InvoiceDate,Price,Customer ID,Country,Preprocessed Description
0,10002,INFLATABLE POLITICAL GLOBE,327,327,327,327,275,327,"[inflatable, political, globe]"
1,10080,GROOVY CACTUS INFLATABLE,6,6,6,6,6,6,"[groovy, cactus, inflatable]"
2,10109,BENDY COLOUR PENCILS,1,1,1,1,1,1,"[bendy, colour, pencil]"
3,10120,DOGGY RUBBER,48,48,48,48,37,48,"[doggy, rubber]"
4,10120,Zebra invcing error,1,1,1,1,0,1,"[zebra, invcing, error]"
...,...,...,...,...,...,...,...,...,...
5065,gift_0001_40,Dotcomgiftshop Gift Voucher Â£40.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£40.00]"
5066,gift_0001_50,Dotcomgiftshop Gift Voucher Â£50.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£50.00]"
5067,gift_0001_70,Dotcomgiftshop Gift Voucher Â£70.00,1,1,1,1,0,1,"[dotcomgiftshop, gift, voucher, Â£70.00]"
5068,gift_0001_80,Dotcomgiftshop Gift Voucher Â£80.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£80.00]"
5069,m,Manual,4,4,4,4,0,4,[manual]

In [17]:
def clean_text(text_vec):
    return ' '.join(text_vec)

df3['clean_text'] = df3['Preprocessed Description'].progress_apply(clean_text)
df3

  0%|          | 0/5070 [00:00<?, ?it/s]

,StockCode,Description,Invoice,Quantity,InvoiceDate,Price,Customer ID,Country,Preprocessed Description,clean_text
0,10002,INFLATABLE POLITICAL GLOBE,327,327,327,327,275,327,"[inflatable, political, globe]",inflatable political globe
1,10080,GROOVY CACTUS INFLATABLE,6,6,6,6,6,6,"[groovy, cactus, inflatable]",groovy cactus inflatable
2,10109,BENDY COLOUR PENCILS,1,1,1,1,1,1,"[bendy, colour, pencil]",bendy colour pencil
3,10120,DOGGY RUBBER,48,48,48,48,37,48,"[doggy, rubber]",doggy rubber
4,10120,Zebra invcing error,1,1,1,1,0,1,"[zebra, invcing, error]",zebra invcing error
...,...,...,...,...,...,...,...,...,...,...
5065,gift_0001_40,Dotcomgiftshop Gift Voucher Â£40.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£40.00]",dotcomgiftshop gift voucher Â£40.00
5066,gift_0001_50,Dotcomgiftshop Gift Voucher Â£50.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£50.00]",dotcomgiftshop gift voucher Â£50.00
5067,gift_0001_70,Dotcomgiftshop Gift Voucher Â£70.00,1,1,1,1,0,1,"[dotcomgiftshop, gift, voucher, Â£70.00]",dotcomgiftshop gift voucher Â£70.00
5068,gift_0001_80,Dotcomgiftshop Gift Voucher Â£80.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£80.00]",dotcomgiftshop gift voucher Â£80.00
5069,m,Manual,4,4,4,4,0,4,[manual],manual

In [7]:
! pip3.9 install scikit-learn

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: scikit-learn in /opt/homebrew/lib/python3.9/site-packages (1.2.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /opt/homebrew/lib/python3.9/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: numpy>=1.17.3 in /opt/homebrew/lib/python3.9/site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: joblib>=1.1.1 in /opt/homebrew/lib/python3.9/site-packages (from scikit-learn) (1.2.0)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3.9 -m pip install --upgrade pip

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
# Create a bag of words from the preprocessed text
vectorizer = CountVectorizer()
bag_of_words = vectorizer.fit_transform(df3['clean_text'])

In [20]:
# Get a list of the words in the bag of words
words = vectorizer.get_feature_names()

# Get the number of appearances of each word
word_counts = bag_of_words.sum(axis=0)

# Create a DataFrame with the word counts
word_counts_df = pd.DataFrame({'word': words, 'count': word_counts.tolist()[0]})

In [21]:
word_counts_df.sort_values(by=['count'],ascending=False).head(20)

           word  count
1395       pink    473
1639        set    416
234        blue    365
1513        red    282
325      candle    272
915       heart    247
2006      white    226
854       glass    224
753      flower    202
1972    vintage    196
1560       rose    188
255         box    185
142         bag    181
217       black    163
412   christmas    157
875       green    154
576      design    153
1170      metal    145
307        cake    143
1080      light    138

In [22]:
import re
colors = ['red', 'orange', 'yellow', 'green', 'blue', 'purple', 'pink', 'brown', 'black', 'white', 'gray']

# Define the function to extract color from preprocessed description
def extract_color(description):
    # Search for colors in the description
    matches = re.findall('|'.join(colors), description, flags=re.IGNORECASE)
    # If no color is found, return None
    if len(matches) == 0:
        return None
    # If multiple colors are found, return the first one
    else:
        return matches[0]

# Apply the function to the 'Preprocessed Description' column to create a new 'Color' column
df3['Color'] = df3['clean_text'].progress_apply(extract_color)

  0%|          | 0/5070 [00:00<?, ?it/s]

In [23]:
df3

,StockCode,Description,Invoice,Quantity,InvoiceDate,Price,Customer ID,Country,Preprocessed Description,clean_text,Color
0,10002,INFLATABLE POLITICAL GLOBE,327,327,327,327,275,327,"[inflatable, political, globe]",inflatable political globe,None
1,10080,GROOVY CACTUS INFLATABLE,6,6,6,6,6,6,"[groovy, cactus, inflatable]",groovy cactus inflatable,None
2,10109,BENDY COLOUR PENCILS,1,1,1,1,1,1,"[bendy, colour, pencil]",bendy colour pencil,None
3,10120,DOGGY RUBBER,48,48,48,48,37,48,"[doggy, rubber]",doggy rubber,None
4,10120,Zebra invcing error,1,1,1,1,0,1,"[zebra, invcing, error]",zebra invcing error,None
...,...,...,...,...,...,...,...,...,...,...,...
5065,gift_0001_40,Dotcomgiftshop Gift Voucher Â£40.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£40.00]",dotcomgiftshop gift voucher Â£40.00,None
5066,gift_0001_50,Dotcomgiftshop Gift Voucher Â£50.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£50.00]",dotcomgiftshop gift voucher Â£50.00,None
5067,gift_0001_70,Dotcomgiftshop Gift Voucher Â£70.00,1,1,1,1,0,1,"[dotcomgiftshop, gift, voucher, Â£70.00]",dotcomgiftshop gift voucher Â£70.00,None
5068,gift_0001_80,Dotcomgiftshop Gift Voucher Â£80.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£80.00]",dotcomgiftshop gift voucher Â£80.00,None
5069,m,Manual,4,4,4,4,0,4,[manual],manual,None

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TF-IDF vectorizer object
vectorizer = TfidfVectorizer()

# Fit the vectorizer to the cleaned descriptions
vectorizer.fit(df3['clean_text'])

# Transform the cleaned descriptions into TF-IDF vectors
vectors = vectorizer.transform(df3['clean_text'])

In [25]:
import spacy

# Load the spacy model
nlp = spacy.load('en_core_web_md')

# Function to get the Word2Vec vector for a list of words
def get_vector(full_text):
    # Initialize an empty vector
    doc = nlp(full_text)

    return doc.vector

# Apply the get_vector function to the cleaned descriptions
df3['word2vec_vector'] = df3['clean_text'].progress_apply(get_vector)
df3
# Print the resulting matrix of vectors
#vectors = np.stack(df2['word2vec_vector'].to_numpy())
#print(vectors)

  0%|          | 0/5070 [00:00<?, ?it/s]

,StockCode,Description,Invoice,Quantity,InvoiceDate,Price,Customer ID,Country,Preprocessed Description,clean_text,Color,word2vec_vector
0,10002,INFLATABLE POLITICAL GLOBE,327,327,327,327,275,327,"[inflatable, political, globe]",inflatable political globe,None,"[-0.82446665, 1.81241, -2.7604334, 1.3104668, ..."
1,10080,GROOVY CACTUS INFLATABLE,6,6,6,6,6,6,"[groovy, cactus, inflatable]",groovy cactus inflatable,None,"[-0.39939335, 1.3122667, -1.8237667, 2.6965332..."
2,10109,BENDY COLOUR PENCILS,1,1,1,1,1,1,"[bendy, colour, pencil]",bendy colour pencil,None,"[-3.5454667, 3.2347336, -2.7622967, 0.39143765..."
3,10120,DOGGY RUBBER,48,48,48,48,37,48,"[doggy, rubber]",doggy rubber,None,"[-0.98595, 2.3052502, -3.0543, 0.9639499, -1.1..."
4,10120,Zebra invcing error,1,1,1,1,0,1,"[zebra, invcing, error]",zebra invcing error,None,"[0.191961, 0.14209998, 0.69523335, -1.1906937,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
5065,gift_0001_40,Dotcomgiftshop Gift Voucher Â£40.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£40.00]",dotcomgiftshop gift voucher Â£40.00,None,"[-2.9365, -4.17414, -5.9251943, -2.978644, -0...."
5066,gift_0001_50,Dotcomgiftshop Gift Voucher Â£50.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£50.00]",dotcomgiftshop gift voucher Â£50.00,None,"[-2.9365, -4.17414, -5.9251943, -2.978644, -0...."
5067,gift_0001_70,Dotcomgiftshop Gift Voucher Â£70.00,1,1,1,1,0,1,"[dotcomgiftshop, gift, voucher, Â£70.00]",dotcomgiftshop gift voucher Â£70.00,None,"[-2.9365, -4.17414, -5.9251943, -2.978644, -0...."
5068,gift_0001_80,Dotcomgiftshop Gift Voucher Â£80.00,2,2,2,2,0,2,"[dotcomgiftshop, gift, voucher, Â£80.00]",dotcomgiftshop gift voucher Â£80.00,None,"[-2.9365, -4.17414, -5.9251943, -2.978644, -0...."
5069,m,Manual,4,4,4,4,0,4,[manual],manual,None,"[2.3491, 0.75755, 0.13215, 1.9341, 3.0071, -2...."

In [26]:
# save df3 to csv
df3.to_csv('online_retail_II_word2vec_v2.csv')

* For now, we don't use PCA

In [27]:
from sklearn.decomposition import PCA

vectors = np.array(df3['word2vec_vector'])

pca = PCA(n_components=100)

vectors_reduced = pca.fit_transform(np.stack(vectors,axis=0))

In [57]:
from sklearn.metrics.pairwise import cosine_similarity

# first, calculate the pairwise cosine similarity between all the vectors
similarity_matrix = cosine_similarity(np.stack(np.array(df3['word2vec_vector']),axis=0))

most_similar_indexes = []
most_similar_cosine_sims = []
for i in range(len(df3)):
    # exclude self-similarity by setting diagonal elements to -1
    similarity_matrix[i, i] = -1
    # get the indices of the 5 rows with the highest cosine similarity
    most_similar_indices = similarity_matrix[i].argsort()[:-6:-1]
    most_similar_indexes.append(np.array(df3.loc[most_similar_indices,"StockCode"]))
    # get the cosine similarity values of the 5 most similar rows
    most_similar_cosine_sim = similarity_matrix[i, most_similar_indices]
    most_similar_cosine_sims.append(most_similar_cosine_sim)

# add the most similar indexes and cosine similarity values as new columns in the dataframe
df3['most_similar_indexes'] = most_similar_indexes
df3['most_similar_cosine_sims'] = most_similar_cosine_sims
# # add the most similar indexes as a new column in the dataframe
# df['most_similar_idx'] = most_similar_indexes
df4 = df3.loc[:,['StockCode','word2vec_vector','most_similar_indexes','most_similar_cosine_sims']]

df4

,StockCode,word2vec_vector,most_similar_indexes,most_similar_cosine_sims
0,10002,"[-0.82446665, 1.81241, -2.7604334, 1.3104668, ...","[75049L, 44234, 21743, 21744, 47016]","[0.6434653, 0.62308276, 0.61678463, 0.6116491,..."
1,10080,"[-0.39939335, 1.3122667, -1.8237667, 2.6965332...","[20988, 84927E, 22487, 84971S, 84971s]","[0.76041794, 0.7056728, 0.70447206, 0.70248836..."
2,10109,"[-3.5454667, 3.2347336, -2.7622967, 0.39143765...","[10133, 10134, 10135, 37471, 90082A]","[0.7640216, 0.7640216, 0.7640216, 0.74690914, ..."
3,10120,"[-0.98595, 2.3052502, -3.0543, 0.9639499, -1.1...","[16258A, 16050, 84509C, 84509c, 21890]","[0.7346558, 0.73154896, 0.7034508, 0.7034508, ..."
4,10120,"[0.191961, 0.14209998, 0.69523335, -1.1906937,...","[46000R, 21900, 20865, 22433, 85232B]","[0.65459305, 0.5508688, 0.5031626, 0.5013682, ..."
...,...,...,...,...
5065,gift_0001_40,"[-2.9365, -4.17414, -5.9251943, -2.978644, -0....","[gift_0001_80, gift_0001_70, gift_0001_50, gif...","[0.9999995, 0.9999995, 0.9999995, 0.9999995, 0..."
5066,gift_0001_50,"[-2.9365, -4.17414, -5.9251943, -2.978644, -0....","[gift_0001_80, gift_0001_70, gift_0001_40, gif...","[0.9999995, 0.9999995, 0.9999995, 0.9999995, 0..."
5067,gift_0001_70,"[-2.9365, -4.17414, -5.9251943, -2.978644, -0....","[gift_0001_80, gift_0001_50, gift_0001_40, gif...","[0.9999995, 0.9999995, 0.9999995, 0.9999995, 0..."
5068,gift_0001_80,"[-2.9365, -4.17414, -5.9251943, -2.978644, -0....","[gift_0001_70, gift_0001_50, gift_0001_40, gif...","[0.9999995, 0.9999995, 0.9999995, 0.9999995, 0..."
5069,m,"[2.3491, 0.75755, 0.13215, 1.9341, 3.0071, -2....","[M, 22083, 47566B, 22654, 22652]","[1.0000001, 0.5305099, 0.52417266, 0.51598203,..."

In [45]:
df3['most_similar_cosine_sims']

0       [0.6434653, 0.62308276, 0.61678463, 0.6116491,...
1       [0.76041794, 0.7056728, 0.70447206, 0.70248836...
2       [0.7640216, 0.7640216, 0.7640216, 0.74690914, ...
3       [0.7346558, 0.73154896, 0.7034508, 0.7034508, ...
4       [0.65459305, 0.5508688, 0.5031626, 0.5013682, ...
                              ...
5065    [0.9999995, 0.9999995, 0.9999995, 0.9999995, 0...
5066    [0.9999995, 0.9999995, 0.9999995, 0.9999995, 0...
5067    [0.9999995, 0.9999995, 0.9999995, 0.9999995, 0...
5068    [0.9999995, 0.9999995, 0.9999995, 0.9999995, 0...
5069    [1.0000001, 0.5305099, 0.52417266, 0.51598203,...
Name: most_similar_cosine_sims, Length: 5070, dtype: object

In [47]:
df3.to_csv("df_most_similar_indexes.csv")

## Function

In [99]:
# Load the spacy model
nlp = spacy.load('en_core_web_md')

# def find_most_similar_products(df3):
    # df3['Preprocessed Description'] = df3['Description'].progress_apply(preprocess_text)
    # df3['clean_text'] = df3['Preprocessed Description'].progress_apply(clean_text)
    # df3['word2vec_vector'] = df3['clean_text'].progress_apply(get_vector)

    # similarity_matrix = cosine_similarity(np.stack(np.array(df3['word2vec_vector']),axis=0))

    # most_similar_indexes = []
    # most_similar_cosine_sims = []
    # for i in range(len(df3)):
    #     # exclude self-similarity by setting diagonal elements to -1
    #     similarity_matrix[i, i] = -1
    #     # get the indices of the 5 rows with the highest cosine similarity
    #     most_similar_indices = similarity_matrix[i].argsort()[:-6:-1]
    #     most_similar_indexes.append(np.array(df3.loc[most_similar_indices,"StockCodeHash"]))
    #     # get the cosine similarity values of the 5 most similar rows
    #     most_similar_cosine_sim = similarity_matrix[i, most_similar_indices]
    #     most_similar_cosine_sims.append(most_similar_cosine_sim)
    # most_similar_cosine_sim = np.stack(most_similar_cosine_sims,axis=0)
    # most_similar_indexes = np.stack(most_similar_indexes,axis=0)

    # # add the most similar indexes and cosine similarity values as new columns in the dataframe
    # df3['most_similar_index_1'] = most_similar_indexes[:,0]
    # df3['most_similar_index_2'] = most_similar_indexes[:,1]
    # df3['most_similar_index_3'] = most_similar_indexes[:,2]
    # df3['most_similar_index_4'] = most_similar_indexes[:,3]
    # df3['most_similar_index_5'] = most_similar_indexes[:,4]

    # df3['most_similar_cosine_1'] = most_similar_cosine_sims[:,0]
    # df3['most_similar_cosine_2'] = most_similar_cosine_sims[:,1]
    # df3['most_similar_cosine_3'] = most_similar_cosine_sims[:,2]
    # df3['most_similar_cosine_4'] = most_similar_cosine_sims[:,3]
    # df3['most_similar_cosine_5'] = most_similar_cosine_sims[:,4]

    # df4 = df3.loc[:,['StockCodeHash','most_similar_index1','most_similar_index2','most_similar_index3','most_similar_index4','most_similar_index5',
    #                  'most_similar_cosine_1','most_similar_cosine_2','most_similar_cosine_3','most_similar_cosine_4','most_similar_cosine_5']]

    # return df4


def find_most_similar_products(df3):
    df3['Preprocessed Description'] = df3['Description'].progress_apply(preprocess_text)
    df3['clean_text'] = df3['Preprocessed Description'].progress_apply(clean_text)
    df3['word2vec_vector'] = df3['clean_text'].progress_apply(get_vector)

    similarity_matrix = cosine_similarity(np.stack(np.array(df3['word2vec_vector']),axis=0))

    most_similar_indexes = []
    most_similar_cosine_sims = []
    sim_ind_1 = []
    sim_ind_2 = []
    sim_ind_3 = []
    sim_ind_4 = []
    sim_ind_5 = []
    sim_cos_1 = []
    sim_cos_2 = []
    sim_cos_3 = []
    sim_cos_4 = []
    sim_cos_5 = []
    
    
    for i in range(len(df3)):
        # exclude self-similarity by setting diagonal elements to -1
        similarity_matrix[i, i] = -1
        # get the indices of the 5 rows with the highest cosine similarity
        best_sim = similarity_matrix[i].argsort()[:-6:-1]     
        sim_ind_1.append(best_sim[0])
        sim_ind_2.append(best_sim[1])
        sim_ind_3.append(best_sim[2])
        sim_ind_4.append(best_sim[3])
        sim_ind_5.append(best_sim[4])
        
        # get the cosine similarity values of the 5 most similar rows
        sim_cos_1.append(similarity_matrix[i, best_sim[0]])
        sim_cos_2.append(similarity_matrix[i, best_sim[1]])
        sim_cos_3.append(similarity_matrix[i, best_sim[2]])
        sim_cos_4.append(similarity_matrix[i, best_sim[3]])
        sim_cos_5.append(similarity_matrix[i, best_sim[4]])

    # add the most similar indexes and cosine similarity values as new columns in the dataframe
    df3["sim_ind_1"] = sim_ind_1
    df3["sim_ind_2"] = sim_ind_2
    df3["sim_ind_3"] = sim_ind_3
    df3["sim_ind_4"] = sim_ind_4
    df3["sim_ind_5"] = sim_ind_5
    
    df3["sim_cos_1"] = sim_cos_1
    df3["sim_cos_2"] = sim_cos_2
    df3["sim_cos_3"] = sim_cos_3
    df3["sim_cos_4"] = sim_cos_4
    df3["sim_cos_5"] = sim_cos_5
    return df3

In [100]:
df2 = df[~df['Description'].isna()]
df3 = df2.groupby(['StockCode','Description'],as_index=False).count()
df4, map_ = encode_stockcode(df3)
df4 = find_most_similar_products(df3)
df4

  0%|          | 0/5070 [00:00<?, ?it/s]

  0%|          | 0/5070 [00:00<?, ?it/s]

  0%|          | 0/5070 [00:00<?, ?it/s]

,Description,Invoice,Quantity,InvoiceDate,Price,Customer ID,Country,StockCodeHash,Preprocessed Description,clean_text,...,sim_ind_1,sim_ind_2,sim_ind_3,sim_ind_4,sim_ind_5,sim_cos_1,sim_cos_2,sim_cos_3,sim_cos_4,sim_cos_5
0,INFLATABLE POLITICAL GLOBE,327,327,327,327,275,327,10002,"[inflatable, political, globe]",inflatable political globe,...,3947,2690,1114,1115,2700,0.643465,0.623083,0.616785,0.611649,0.609330
1,GROOVY CACTUS INFLATABLE,6,6,6,6,6,6,10080,"[groovy, cactus, inflatable]",groovy cactus inflatable,...,370,4390,1923,4456,4457,0.760418,0.705673,0.704472,0.702488,0.702488
2,BENDY COLOUR PENCILS,1,1,1,1,1,1,10109,"[bendy, colour, pencil]",bendy colour pencil,...,6,7,8,2665,4843,0.764022,0.764022,0.764022,0.746909,0.746019
3,DOGGY RUBBER,48,48,48,48,37,48,10120,"[doggy, rubber]",doggy rubber,...,3458,33,4118,4129,1253,0.734656,0.731549,0.703451,0.703451,0.661971
4,Zebra invcing error,1,1,1,1,0,1,10120,"[zebra, invcing, error]",zebra invcing error,...,3699,1265,284,1858,4717,0.654593,0.550869,0.503163,0.501368,0.493487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5065,Dotcomgiftshop Gift Voucher Â£40.00,2,2,2,2,0,2,-2360902159825774783,"[dotcomgiftshop, gift, voucher, Â£40.00]",dotcomgiftshop gift voucher Â£40.00,...,5068,5067,5066,5064,5063,1.000000,1.000000,1.000000,1.000000,1.000000
5066,Dotcomgiftshop Gift Voucher Â£50.00,2,2,2,2,0,2,8725189771270228549,"[dotcomgiftshop, gift, voucher, Â£50.00]",dotcomgiftshop gift voucher Â£50.00,...,5068,5067,5065,5064,5063,1.000000,1.000000,1.000000,1.000000,1.000000
5067,Dotcomgiftshop Gift Voucher Â£70.00,1,1,1,1,0,1,-7530139991614082478,"[dotcomgiftshop, gift, voucher, Â£70.00]",dotcomgiftshop gift voucher Â£70.00,...,5068,5066,5065,5064,5063,1.000000,1.000000,1.000000,1.000000,1.000000
5068,Dotcomgiftshop Gift Voucher Â£80.00,2,2,2,2,0,2,5829484553763587174,"[dotcomgiftshop, gift, voucher, Â£80.00]",dotcomgiftshop gift voucher Â£80.00,...,5067,5066,5065,5064,5063,1.000000,1.000000,1.000000,1.000000,1.000000
5069,Manual,4,4,4,4,0,4,594513457150200941,[manual],manual,...,5055,1419,3758,2124,2122,1.000000,0.530510,0.524173,0.515982,0.498022

In [101]:
df4.to_csv("df_most_similar_indexes.csv")